name: Jill

on:
  push:
    branches: ['main']
    paths:
      - 'apps/jill/**'
  pull_request:
    branches: ['main']
    paths:
      - 'apps/jill/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REACT_APP_PRODUCTION: ${{secrets.JILL_REACT_APP_PRODUCTION}}
  REACT_APP_API_URL: ${{secrets.JILL_REACT_APP_API_URL}}
  REACT_APP_FIREBASE_CONFIG: ${{secrets.JILL_REACT_APP_FIREBASE_CONFIG}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ./pet-documents
            sh ./scripts/git-pull.sh
            sh ./scripts/deploy-jill.sh
