name: Deploy Jill

on:
  workflow_run:
    workflows: ['Build Apps']
    branches: [main]
    types: [completed]
    push:
      branches: ['main']
      paths:
        - 'apps/jill/**'
        - 'libs/types/**'
    pull_request:
      branches: ['main']
      paths:
        - 'apps/jill/**'
        - 'libs/types/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy Jill
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ./pet-documents
            sh ./scripts/deploy-jill.sh
