# This is a basic workflow to help you get started with Actions

name: Build & Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd testDeploy/pet-documents
            git pull
            cd ./apps/trixie
            touch .production.env
            cat > .production.env <<EOF
              DATABASE_URL=${{secrets.TRIXIE_DATABASE_URL}}
              PORT=${{secrets.TRIXIE_PORT}}
              FB_BUCKET_URL=${{secrets.TRIXIE_FB_BUCKET_URL}}
            EOF

            echo Deploy Successful
