# This is a basic workflow to help you get started with Actions

name: Build & Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{SECRET.SSH_HOST}}
          key: ${{SECRET.SSH_KEY}}
          username: ${{SECRET.SSH_USERNAME}}
          script: |
            mkdir testDeploy
            cd testDeploy
            git clone git@github.com:badgers-ua/pet-documents.git
            echo Deploy Successful
