name: Deploy Trixie

on:
  workflow_run:
    workflows: ['Build Apps']
    branches: [main]
    types:
      - completed
  push:
    branches: ['main']
    paths:
      - 'apps/trixie/**'
  pull_request:
    branches: ['main']
    paths:
      - 'apps/trixie/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy Trixie
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ./pet-documents
            sh ./scripts/deploy-trixie.sh
